name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: acrtestingaks
  IMAGE_NAME: simple-python-app
  AKS_RESOURCE_GROUP: rg-sumaira-practice
  AKS_CLUSTER_NAME: AKS-test-github-actions
  LOGIN_SERVER: acrtestingaks.azurecr.io

jobs:
  build-and-deploy:
    runs-on: linux

    steps:
    # 1. Login to ACR 
    - uses: actions/checkout@v3
    - name: Azure ACR Login
      run: |
         az login --identity
         az acr login --name ${{ env.ACR_NAME }}
      
    # 2. Build and Push Docker Image
    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker push ${{ env.LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
    
    - name: Azure Login with Personal Account
      run: |
          az login --identity
          az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
    # 3. Get AKS Credentials (needs Azure CLI login or kubeconfig)


    - name: Get AKS credentials
      run: |
          az aks get-credentials \
            --resource-group $AKS_RESOURCE_GROUP \
            --name $AKS_CLUSTER_NAME \
            --overwrite-existing
            
    - name: Debug - list all files
      run: ls -R
    
    # 4. Deploy to AKS
    - name: Deploy to AKS
      run: |
          kubectl apply -f aks/deployment.yaml
          kubectl set image deployment/simple-python-app simple-python-app=$LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}
          kubectl rollout status deployment/simple-python-app
          
